In [9]:
import numpy
A = matrix(QQ, [[4,  -1,  -2],
                [2,   1,  -2],
                [1,  -1,   1]])



E_mat = matrix(QQ, [[1,   3,   0],
                    [2,   3,   0],
                    [0,   2,  -3]])

show("A_mat = ",A)
show("E_mat = ",E_mat)

'A_mat = ' [ 4 -1 -2]
[ 2  1 -2]
[ 1 -1  1]

'E_mat = ' [ 1  3  0]
[ 2  3  0]
[ 0  2 -3]

In [10]:
B = E_mat**(-1)*A*E_mat
show("Пункт 1")
show("Матрица A' = S^-1 * A * S = ", B)

'Пункт 1'

"Матрица A' = S^-1 * A * S = " [  2   0   0]
[  0 5/3   2]
[1/3 4/9 7/3]

In [11]:
var('lam')
P = A - lam*identity_matrix(3)
show("P_mat = ",P)

'P_mat = ' [-lam + 4       -1       -2]
[       2 -lam + 1       -2]
[       1       -1 -lam + 1]

In [12]:
show("Пункт 2")
show(f'характеристический многочлен = {det(P)}')

'Пункт 2'

'характеристический многочлен = -((lam - 1)^2 - 2)*(lam - 4) - 4*lam + 10'

In [16]:
show("Пункт 3")
show('Характеристические числа преобразования')
res = solve(det(P), lam)
for i in range(0,3):
    show(res[i].rhs().n(digits = 5))
#     show("Lam ",res[i].rhs().n(digits = 5))

'Пункт 3'

'Характеристические числа преобразования'

1.0000

2.0000

3.0000

In [14]:
show("Пункт 4")
show('собственные значения')
for i in range(0,3):
    if (not res[i].rhs().n(digits = 5).imag()):
        show(f'lam = {res[i].rhs().n(digits = 5)}')

'Пункт 4'

'собственные значения'

'lam = 1.0000'

'lam = 2.0000'

'lam = 3.0000'